// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int N = Integer.parseInt(args[0]);
		double big =0, small =0;
		for(int i=0; i < N; i++)
		{
			double rnd = Math.random();
			if (rnd>0.5) {
				big++;
			}
			else
			{
				small++;
			}

		}
		double ratio;
		if (small>0 && big>0) {
			if (big>small) {
				ratio = small / big;
			}
			else
			{
				ratio = big / small;
			}
			System.out.println("> 0.5: " + (int)big + " times");
			System.out.println("<= 0.5: " + (int)small + " times");
			System.out.println("Ratio: " + ratio);
		}
		else{
			System.out.println("> 0.5: " + (int)big + " times");
			System.out.println("<= 0.5: " + (int)small + " times");
		}
	}
}
